CREATE TABLE IF NOT EXISTS person
(
    id    int GENERATED BY DEFAULT AS IDENTITY,
    name  varchar(100),
    age   int,
    email varchar(100)
);

ALTER TABLE person
    ALTER COLUMN name SET NOT NULL;

INSERT INTO Person (name, age, email)
VALUES ('Tony Stark', 48, 'tony.stark@starkindustries.com'),
       ('Bruce Wayne', 42, 'bruce.wayne@wayneenterprises.com'),
       ('Diana Prince', 3000, 'diana.prince@themyscira.com'),
       ('Peter Parker', 17, 'peter.parker@dailybugle.com'),
       ('Clark Kent', 35, 'clark.kent@dailyplanet.com'),
       ('Natasha Romanoff', 34, 'natasha.romanoff@shield.com'),
       ('Steve Rogers', 100, 'steve.rogers@avengers.com'),
       ('Bruce Banner', 40, 'bruce.banner@avengers.com'),
       ('Wanda Maximoff', 29, 'wanda.maximoff@avengers.com'),
       ('Stephen Strange', 45, 'stephen.strange@sorcerersupreme.com');

ALTER TABLE person
    ADD COLUMN created_at timestamp,
    ADD COLUMN updated_at timestamp,
    ADD COLUMN created_by varchar(100);

CREATE TABLE IF NOT EXISTS sensor
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS measurement
(
    id        int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    value     double precision NOT NULL,
    raining   boolean NOT NULL,
    created_at timestamp NOT NULL,
    sensor_id int REFERENCES sensor (id)
);

ALTER TABLE measurements
    ADD COLUMN created_at timestamp;

ALTER TABLE measurements
    RENAME TO measurement;

TRUNCATE TABLE measurement;
